%% Choose one patch to generate initial condition on interactively, among those
%% previously generated by bccomics_setup

%% read in V_cb field: V_cb = Vc-Vb
if matlabflag
  load([setupdir '/V_cb_1_azend.dat'], '-mat', 'V_cb_1_azend');  
  load([setupdir '/V_cb_2_azend.dat'], '-mat', 'V_cb_2_azend');
  load([setupdir '/V_cb_3_azend.dat'], '-mat', 'V_cb_3_azend');
  load([setupdir '/DT_azend.dat'],     '-mat', 'DT3D_azend');
  load([setupdir '/Dc3D_azend.dat'],   '-mat', 'Dc3D_azend');
  load([setupdir '/Db3D_azend.dat'],   '-mat', 'Db3D_azend');
  load([setupdir '/THc3D_azend.dat'],  '-mat', 'THc3D_azend');
  load([setupdir '/THb3D_azend.dat'],  '-mat', 'THb3D_azend');
else
  load('-mat-binary', [setupdir '/V_cb_1_azend.dat'], 'V_cb_1_azend');
  load('-mat-binary', [setupdir '/V_cb_2_azend.dat'], 'V_cb_2_azend');
  load('-mat-binary', [setupdir '/V_cb_3_azend.dat'], 'V_cb_3_azend');
  load('-mat-binary', [setupdir '/DT_azend.dat'],     'DT3D_azend');
  load('-mat-binary', [setupdir '/Dc3D_azend.dat'],   'Dc3D_azend');
  load('-mat-binary', [setupdir '/Db3D_azend.dat'],   'Db3D_azend');
  load('-mat-binary', [setupdir '/THc3D_azend.dat'],  'THc3D_azend');
  load('-mat-binary', [setupdir '/THb3D_azend.dat'],  'THb3D_azend');
end

%% choose patch whose small scale fluctuations to calculate
cellspec = load([setupdir '/zi_icc_Dc_Db_Thc_Thb_Vcb1_Vcb2_Vcb3_Vcb_DT.dat']);
Ncc = length(cellspec(:,1)); %% # of chosen patchess

cellspec_azend = load([setupdir '/zend_icc_Dc_Db_Thc_Thb_Vcb1_Vcb2_Vcb3_Vcb_DT.dat']);
Ncc_azend = length(cellspec_azend(:,1)); %% # of chosen patchess

%% read in z=zi=1000 statistics
fin=fopen([setupdir '/stats_zi.dat']);
fgets(fin); %% skip a line
fgets(fin); %% skip another line
statszi = fscanf(fin, '%e %e %e %e %e %e %e %e %e');
fclose(fin);

%% Let user choose a patch
disp('Patches ordered in calculation time, from oldest(top) to newest(bottom)');
disp('-----------------------------------------------------------------------');
disp('Patch #  ix  iy  iz  Deltac/sigma(Deltac)  V_cb(km/s)  at z=1000');
for ip=1:Ncc
  AA = [ip cellspec(ip,1) cellspec(ip,2) cellspec(ip,3) cellspec(ip,4)/statszi(1) cellspec(ip,11)];
  fprintf('%3i     %3i %3i %3i     %10.3e         %10.3e\n',AA);
end
disp(['Choose a patch of your interest; default is ' num2str(Ncc) ' if you just hit Enter below.']);
idxcc = input('Enter your choice (patch #):');
if isempty(idxcc)  %% default to the last patch calculated
  idxcc=Ncc;
end
disp(['Patch # ' num2str(idxcc) ' chosen.']);

%% Do sanity check
ic   = cellspec(idxcc,1);
jc   = cellspec(idxcc,2);
kc   = cellspec(idxcc,3);

vratio = norm([V_cb_1_azend(ic,jc,kc) V_cb_2_azend(ic,jc,kc) V_cb_3_azend(ic,jc,kc)])/cellspec_azend(idxcc,11);
dratio = Dc3D_azend(ic,jc,kc)/cellspec_azend(ip,4)
if (vratio>1.01 | vratio <0.99)
  disp(['V_cb_*_azend.dat and ' setupdir '/zi_icc_Dc_Db_Thc_Thb_Vcb1_Vcb2_Vcb3_Vcb_DT.dat mismatch.']);
  disp('Rerun bccomics_setup, and pick the newly written files.');
  returnflag = true;
  return;
end
if (dratio>1.01 | dratio <0.99)
  disp(['Dc3D_azend.dat and ' setupdir '/zi_icc_Dc_Db_Thc_Thb_Vcb1_Vcb2_Vcb3_Vcb_DT.dat mismatch.']);
  disp('Rerun bccomics_setup, and pick the newly written files.');
  returnflag = true;
  return;
end
